dev:
    .settings:
#        error_reporting: <?php echo ((E_ALL | E_STRICT) ^ E_DEPRECATED)."\n" ?>
    error_reporting: <?php echo E_ALL & ~E_DEPRECATED ."\n" ?>
    
test:
    .settings:
#        error_reporting: <?php echo ((E_ALL | E_STRICT) ^ E_DEPRECATED)."\n" ?>
    error_reporting: <?php echo E_ALL & ~E_DEPRECATED ."\n" ?>